services:
  dev-db:
    image: postgres:18.1
    container_name: schuly-postgres-dev
    restart: always
    environment:
      POSTGRES_PASSWORD: d4vpas8w0rd13!!!
      POSTGRES_DB: schuly-dev
    ports:
      - "2406:5432"
    volumes:
      - postgres-data-dev:/var/lib/postgresql

  dev-s3:
    image: chrislusf/seaweedfs:latest
    container_name: schuly-s3-dev
    restart: always
    command: >
      server -dir=/data
      -s3 -s3.config=/etc/seaweedfs/s3-config.json
      -s3.port=8333
      -master.volumeSizeLimitMB=1024
    ports:
      - "8333:8333"  # S3 API
      - "9333:9333"  # master UI
      - "8888:8888"  # filer
    volumes:
      - ./data/seaweedfs:/data
      - ./scripts/seaweedfs/s3-config.json:/etc/seaweedfs/s3-config.json:ro

  dev-schulware:
    image: ghcr.io/pianonic/schulwareapi:latest
    container_name: schuly-schulware-dev
    restart: unless-stopped
    init: true
    ipc: host
    environment:
      - PYTHONUNBUFFERED=1
      - SCHULNETZ_CLIENT_ID=ppyybShnMerHdtBQ
      - SCHULNETZ_WEB_BASE_URL=https://schulnetz.web.app
    ports:
      - "8000:8000"

volumes:
  postgres-data-dev: